name: Check-All

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

env:
  GH_SBT_OPTS: "-Xss64m -Xms1024m -XX:MaxMetaspaceSize=1G -Xmx8G -XX:MaxInlineLevel=18 -XX:+UnlockExperimentalVMOptions"

jobs:

  build-and-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.12.18", binary-version: "2.12", java-version: "11", java-distribution: "temurin", report: "" }
          - { name: "Scala 2", version: "2.13.16", binary-version: "2.13", java-version: "11", java-distribution: "temurin", report: "" }
    #          - { name: "Scala 3", version: "3.3.5",   binary-version: "3",    java-version: "11", java-distribution: "temurin", report: "" }

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.scala.java-version }}
          distribution: ${{ matrix.scala.java-distribution }}
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: "[Push] Build All for ${{ matrix.scala.name }} v${{ matrix.scala.version }} - ${{ github.run_number }}"
        if: github.event_name == 'push'
        env:
          CURRENT_BRANCH_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          SBT_OPTS: ${{ env.GH_SBT_OPTS }}
        run: |
          echo "[BEFORE]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
          export CURRENT_BRANCH_NAME="${CURRENT_BRANCH_NAME#refs/heads/}"
          echo " [AFTER]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
          echo "RUN_ID=${RUN_ID}"
          echo "RUN_NUMBER=${RUN_NUMBER}"
          echo "Push #${PUSH_NUMBER}"
          java -version
          echo "SBT_OPTS=${SBT_OPTS}"
          echo "SBT_OPTS=${SBT_OPTS}"
          sbt \
            ++${{ matrix.scala.version }} \
            "scalafixAll --check" \
            scalafmtCheckAll

      - name: "[PR] Build All for ${{ matrix.scala.name }} v${{ matrix.scala.version }} - PR-#${{ github.event.pull_request.number }} - ${{ github.run_number }}"
        if: github.event_name == 'pull_request'
        env:
          CURRENT_BRANCH_NAME: ${{ github.base_ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SBT_OPTS: ${{ env.GH_SBT_OPTS }}
        run: |
          echo "Rull request to the '${CURRENT_BRANCH_NAME}' branch"
          echo "RUN_ID=${RUN_ID}"
          echo "RUN_NUMBER=${RUN_NUMBER}"
          echo "PR #${PR_NUMBER}"
          java -version
          echo "SBT_OPTS=${SBT_OPTS}"
          echo "SBT_OPTS=${SBT_OPTS}"
          sbt \
            ++${{ matrix.scala.version }} \
            "scalafixAll --check" \
            scalafmtCheckAll
