name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-

      - name: sbt GitHub Release LoggerF
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
        run: |
          echo "Run] sbt GitHub release"
          echo 'sbt -J-Xmx2048m clean +test +packagedArtifacts'
          sbt \
            -J-Xmx2048m \
            clean \
            +test \
            +packagedArtifacts
          echo "====================="
          echo 'sbt -J-Xmx2048m gitHubRelease'
          sbt \
            -J-Xmx2048m \
            gitHubRelease


  publish:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.11.12", binary-version: "2.11", java-version: "8" }
          - { version: "2.12.12", binary-version: "2.12", java-version: "11" }
          - { version: "2.13.3",  binary-version: "2.13", java-version: "11" }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.scala.java-version }}

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-

      - name: sbt Publish LoggerF
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          echo "Run] sbt publish All for Scala ${{ matrix.scala.version }}"
          echo 'sbt -J-Xmx2048m ++${{ matrix.scala.version }}! -v clean publish'
          sbt \
            -J-Xmx2048m \
            ++${{ matrix.scala.version }}! \
            -v \
            clean \
            publish

  publish_maven:
    needs: publish
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync LoggerF to Maven Central
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export GITHUB_TAG=${GITHUB_REF#refs/tags/}
          .github/workflows/maven_central_sync.sh
